import type { Metadata } from "next";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { PalmMarkdown } from "@/components/PalmMarkdown";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "The terms that govern using Palmistica.",
};

const TERMS_BODY = `
## What Palmistica Is

Palmistica generates AI-based palm readings for curiosity and entertainment purposes only. Readings are generated by an AI model and are not based on any scientifically validated method of palmistry, prediction, or personality analysis. **Palmistica is not a source of medical, financial, psychological, or legal advice, and nothing on this site should be treated as such.** Decisions about your health, finances, relationships, or life direction should not be based on your Palmistica reading.

## Who Can Use Palmistica

Palmistica is not intended for children under 13. By using the service, you confirm you meet this minimum age requirement (or the minimum digital consent age in your jurisdiction, if higher).

## Your Content

You retain ownership of any photo you upload. By uploading a photo, you grant Palmistica a limited license to process it (including sending it to our AI provider) solely to generate your reading, and, if you choose to keep and share your reading, to display it at your shareable link. You're responsible for the photo you upload; don't upload photos of anyone without their consent, and don't upload anything illegal, harmful, or that isn't actually a palm photo.

We reserve the right to remove any reading or restrict access to the service if we reasonably believe it's being misused.

## Sharing

Any reading you create can be viewed by anyone who has its unique share link. Palmistica is not responsible for what happens after you share that link with others; sharing is your choice and your responsibility.

## Tips

Tips are entirely voluntary and are not a purchase of any product, service, or feature, Palmistica remains free either way. Tips are processed by Stripe and are generally non-refundable, since no specific good or service is exchanged for a tip. If you believe a tip was made in error, contact us at ranjithnair.ai@gmail.com and we'll do our best to help.

## No Warranty

Palmistica is provided "as is," without warranties of any kind. We don't guarantee the accuracy, reliability, or availability of readings or the service, and we're not liable for any decisions made based on a reading.

## Limitation of Liability

To the fullest extent permitted by law, Palmistica and its operator are not liable for any indirect, incidental, or consequential damages arising from your use of the service.

## Changes

We may update these terms from time to time. Continued use of Palmistica after changes means you accept the updated terms.

## Governing Law

These terms are governed by the laws of Canada, without regard to conflict-of-law principles.

## Contact

Questions about these terms can be sent to ranjithnair.ai@gmail.com.
`.trim();

export default function TermsOfUsePage() {
  return (
    <>
      <SiteHeader />

      <main className="relative z-10 mx-auto w-full max-w-3xl flex-1 px-6 py-16">
        <p className="eyebrow">Legal</p>
        <h1 className="mt-3 font-serif text-3xl sm:text-4xl">Terms of Use</h1>
        <p className="mt-2 text-sm text-cream-faint">Last updated: September 18, 2026</p>
        <p className="mt-6 max-w-2xl text-sm leading-relaxed text-cream-muted">
          Welcome to Palmistica. By using palmistica.com, you agree to these terms.
          Please read them.
        </p>

        <hr className="hairline my-8" />

        <PalmMarkdown>{TERMS_BODY}</PalmMarkdown>
      </main>

      <SiteFooter />
    </>
  );
}
